ALTER TABLE "aerodromes" ADD COLUMN IF NOT EXISTS "fuelUpdatedAt" TIMESTAMP(3);
ALTER TABLE "aerodromes" ADD COLUMN IF NOT EXISTS "taxUpdatedAt" TIMESTAMP(3);
ALTER TABLE "aerodromes" ADD COLUMN IF NOT EXISTS "notesUpdatedAt" TIMESTAMP(3);
